name: PlayerGender
version: '${project.version}'
main: cn.paper_card.player_gender.PlayerGender
api-version: '1.20'
author: Paper99
folia-supported: true

commands:
  gender:
    permission: gender.command

permissions:
  gender.command:
    default: op